services:
  postgres:
    image: postgres:10.10-alpine
    env_file: .env
    ports:
      - "5435:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  django:
    build: ./src
    command: ./django-entrypoint-loc.sh
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./src:/src/
    ports:
      - "8000:8000"
#    expose:
#      - 8000

  redis:
    image: "redis:alpine"

  celery:
    build: ./src
    command: watchmedo auto-restart --directory=/usr/src/app/ --pattern=*.py --recursive -- celery -A backend worker -l info -E -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
    env_file: .env
    volumes:
      - ./src:/usr/src/app

#  nginx:
#    image: nginx:latest
#    depends_on:
#      - django
#    ports:
#      - "9000:80"
#      - "443:443"
#    volumes:
#      - ./nginx/loc/conf:/etc/nginx/conf.d/:ro
#      - ./nginx/loc/ssl:/etc/ssl/:ro
#      - ./src/static/:/src/static
#      - ./src/media/:/src/media
